[package]
name = "leaks"
version = "0.1.0"
edition = "2024"

[lib]
name = "leaks"
crate-type = ["cdylib"]

[dependencies]
desim = "0.4.0"
rand = {version = "0.8.3", features = ["small_rng"]}
rand_distr = "0.4"
pyo3 = { version = "0.21.2", features = ["extension-module"] }
petgraph = "0.8.3"
pathfinding = "4.9.0"

[dev-dependencies]
rand = {version = "0.8.3", features = ["small_rng"]}
rand_distr = "0.4"
